import {it,expect,vi} from 'vitest';
import {essayEvaluationGateway} from './gateway';
const a='00000000-0000-4000-8000-000000000001',e='00000000-0000-4000-8000-000000000002';
const request=(retry?:string)=>new Request('https://test.example/api/essay/evaluate',{method:'POST',headers:{origin:'https://test.example',authorization:'Bearer synthetic'},body:JSON.stringify({attempt_id:a,...(retry?{retry_evaluation_id:retry}:{})})});
function fixture(){const ownedAttempt=vi.fn(async()=>({questionId:a,metadataVersion:'frozen-v1'})),requestEvaluation=vi.fn(async()=>e),authenticate=vi.fn(async()=>true);
 const fetch=vi.fn(async(r:Request)=>r.url.endsWith('/admission')?Response.json({version:'essay-worker-admission-v1',ready:true,questionId:a,metadataVersion:'frozen-v1',regime:'essay-v1.3/policy/'+'a'.repeat(64),expiresAt:Date.now()+60000}):Response.json({}));
 const ports={enabled:true,origin:'https://test.example',authenticate,ownedAttempt,requestEvaluation,releasedFailure:vi.fn(async()=>true),worker:{fetch}};return {...ports,fetch,ports};}
it('unconfigured worker cannot create a reservation',async()=>{const p=fixture();p.ports.enabled=false;expect((await essayEvaluationGateway(p.ports)(request())).status).toBe(503);expect(p.requestEvaluation).not.toHaveBeenCalled();expect(p.fetch).not.toHaveBeenCalled();});
it('foreign attempt fails before worker admission',async()=>{const p=fixture();p.ownedAttempt.mockRejectedValue(Error('owner denied'));expect((await essayEvaluationGateway(p.ports)(request())).status).toBe(409);expect(p.fetch).not.toHaveBeenCalled();expect(p.requestEvaluation).not.toHaveBeenCalled();});
it('incomplete or wrong-question admission cannot reserve Credit',async()=>{const p=fixture();p.fetch.mockResolvedValue(Response.json({version:'essay-worker-admission-v1',ready:true,questionId:e}));expect((await essayEvaluationGateway(p.ports)(request())).status).toBe(503);expect(p.requestEvaluation).not.toHaveBeenCalled();});
it('server regime and stable key are reused after ambiguous worker dispatch',async()=>{const p=fixture();const original=p.fetch.getMockImplementation()!;p.fetch.mockImplementation(async r=>{if(r.url.endsWith('/evaluate'))throw Error('unknown timeout');return original(r);});const handler=essayEvaluationGateway(p.ports);expect(await(await handler(request())).json()).toEqual({code:'STATUS_CHECK_REQUIRED',evaluation_id:e});expect(await(await handler(request())).json()).toEqual({code:'STATUS_CHECK_REQUIRED',evaluation_id:e});expect(p.requestEvaluation.mock.calls[0]).toEqual(p.requestEvaluation.mock.calls[1]);expect(p.requestEvaluation).toHaveBeenCalledTimes(2);});
it('worker completion prose is never treated as stored completion',async()=>{const p=fixture();expect(await(await essayEvaluationGateway(p.ports)(request())).json()).toEqual({code:'STATUS_CHECK_REQUIRED',evaluation_id:e});});

it('unconfirmed failure cannot create a new billing request',async()=>{const p=fixture();p.ports.releasedFailure.mockResolvedValue(false);expect((await essayEvaluationGateway(p.ports)(request(e))).status).toBe(409);expect(p.requestEvaluation).not.toHaveBeenCalled();expect(p.fetch).not.toHaveBeenCalled();});
it('released failure retry has a stable distinct key bound to the failed evaluation',async()=>{const p=fixture();const handler=essayEvaluationGateway(p.ports);await handler(request());await handler(request(e));await handler(request(e));expect(p.requestEvaluation.mock.calls[0]).not.toEqual(p.requestEvaluation.mock.calls[1]);expect(p.requestEvaluation.mock.calls[1]).toEqual(p.requestEvaluation.mock.calls[2]);expect(p.ports.releasedFailure).toHaveBeenCalledWith('synthetic',a,e);});
