import {it,expect,vi} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {filterExams,loadExams,loadQuestion,loadQuestions,officialUrl,type Exam} from './catalog';
const base:Exam={id:'00000000-0000-4000-8000-000000000001',university_id:'u',admission_year:2025,exam_name:'언어형 1교시',exam_kind:'admission',campus:'서울',field_or_division:'인문',admission_track:'논술',official_source_url:'https://example.edu',universities:{name:'합성대',slug:'fixture'}};
it('keeps campus and actual exam year separate from admissions year',()=>{const rows=[base,{...base,id:'2',campus:'세종'},{...base,id:'3',admission_year:2024}];expect(filterExams(rows,'인문','2025','서울')).toEqual([base]);expect(filterExams(rows,'합성','2027','')).toEqual([]);});
it('source links reject script and credential-bearing urls',()=>{expect(officialUrl('javascript:alert(1)')).toBeNull();expect(officialUrl('https://u:p@example.edu')).toBeNull();expect(officialUrl('http://example.edu/official')).toBe('http://example.edu/official');});
function fixture(){const calls:string[][]=[];const query:Record<string,unknown>={};for(const method of ['select','eq','order','limit','abortSignal','maybeSingle'])query[method]=(...a:unknown[])=>{calls.push([method,...a.map(String)]);return query;};query.then=(resolve:(v:unknown)=>void)=>resolve({data:[],error:null});const from=vi.fn(()=>query);return {client:{from} as unknown as SupabaseClient,calls,from};}
it('catalog delegates visibility to existing RLS and explicit active/verified filters',async()=>{const f=fixture();await loadExams(f.client);expect(f.from).toHaveBeenCalledWith('essay_exams');expect(f.calls).toContainEqual(['eq','verification_status','verified']);expect(f.calls).toContainEqual(['eq','universities.is_active','true']);expect(f.calls).toContainEqual(['limit','200']);});
it('question reads never admit unpublished candidates and reject malformed IDs before IO',async()=>{const f=fixture();await expect(loadQuestion(f.client,'wrong')).rejects.toThrow('INVALID_QUESTION');expect(f.from).not.toHaveBeenCalled();await loadQuestions(f.client,base.id);expect(f.calls).toContainEqual(['eq','is_published','true']);expect(f.calls).toContainEqual(['eq','essay_exam_id',base.id]);});
