'use client';
import {useState} from 'react';
import Link from 'next/link';
import {searchResearch,type ResearchCatalog,type ResearchOffering} from '@/lib/essay-research/catalog';
export function ResearchCatalogView({catalog}:{catalog:ResearchCatalog}){
 const [query,setQuery]=useState(''),[region,setRegion]=useState('all');
 const rows=searchResearch(catalog,query,region);
 const universities=[...new Map(rows.map(o=>[o.universityId,{id:o.universityId,name:o.name}])).values()];
 return <section className="catalog-filter"><h2>대학 찾기</h2><p role="status">내부 연구 미리보기 · {catalog.asOf} 기준 · 운영 공개 및 첨삭 연결 전</p><div className="catalog-filter__controls"><label>대학·캠퍼스·전형 검색<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>지역<select value={region} onChange={e=>setRegion(e.target.value)}><option value="all">전체</option><option value="seoul">서울</option><option value="nonseoul">비서울</option></select></label></div><p>{universities.length}개 대학 · {rows.length}개 전형 후보</p><div className="university-grid">{universities.map(u=><article className="university-card" key={u.id}><h3>{u.name}</h3><p>{[...new Set(rows.filter(o=>o.universityId===u.id).map(o=>o.campus))].join(' / ')}</p><Link href={`/essay-lab/universities/${u.id}/2027/`}>2027학년도 전형 보기</Link></article>)}</div>{!rows.length&&<p>일치하는 대학이 없습니다.</p>}</section>;
}
function Offering({o}:{o:ResearchOffering}){return <article className="surface-card" style={{overflowWrap:'anywhere',minWidth:0}}><h2>{o.campus} · {o.admissionNames.join(' / ')}</h2><p>{o.sourceStatus} · 원자료 확인일 {o.checkedAt}</p>{o.metadataState==='QUARANTINED'&&<p role="alert">검토 보류: 기준일 이후 공지 언급이 있습니다. 원자료를 정정하지 않았습니다.</p>}<h3>계열·트랙</h3><ul>{o.tracks.map(t=><li key={t.id}>{t.type} · {t.label} · {t.status}<p>잠정 문제 형식 {t.problemFormat} / 답안 형식 {t.answerFormat} / 입력 방식 {t.inputModes.join(', ')} · 형식 근거 {t.formatEvidence} · 입력 근거 {t.inputEvidence}</p></li>)}</ul><h3>전형별 원자료</h3>{o.rawMaster.map(r=><details key={r.inventory_id}><summary>{r.inventory_id} · {r.recruitment_track}</summary><dl className="metadata-list">{[['모집단위·계열',r.essay_type],['모집인원',r.intake_count],['일정',r.exam_date],['수능최저',r.csat_minimum],['논술 반영',r.essay_weight],['학생부 반영',r.school_record_weight],['검증 상태',r.evidence_status]].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><p>{r.notes}</p></details>)}<h3>공식 출처</h3><ul>{o.sources.map(s=><li key={s}><a href={s} target="_blank" rel="noopener noreferrer">{new URL(s).hostname}의 원자료 ↗</a></li>)}</ul><h3>기출문제와 첨삭</h3><p>이 전형에 연결·검증된 기출문제가 없습니다. 과거 기출의 학년도와 평가 패키지는 별도 검증합니다.</p><button className="button button--outline" disabled>첨삭 연결 전</button></article>}
export function ResearchUniversityView({catalog,id,year}:{catalog:ResearchCatalog;id:string;year?:string}){
 const rows=catalog.offerings.filter(o=>o.universityId===id&&(!year||String(o.year)===year));if(!rows.length)return null;
 return <div className="page-section content-wrap content-wrap--detail"><Link href="/essay-lab/universities/">← 대학 찾기</Link><header className="detail-hero"><div><h1>{rows[0].name} · 2027학년도</h1><p>내부 연구 미리보기 · 원자료 기준일 {catalog.asOf}. 전형 정보 확인과 AI 첨삭 가능 여부는 별개입니다.</p></div></header>{!year?<Link className="button button--outline" href={`/essay-lab/universities/${id}/2027/`}>2027학년도 전형 보기</Link>:rows.map(o=><Offering key={o.id} o={o}/>)}</div>;
}
